services:
  - type: web
    name: emergency-minute
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0